DROP TABLE IF EXISTS CLIMATE_DETAIL;

CREATE TABLE CLIMATE_DETAIL (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  date DATE DEFAULT NULL,
  text VARCHAR(2000) NOT NULL,
  place VARCHAR(250) DEFAULT NULL,
  page_number VARCHAR(10) DEFAULT NULL,
  book_name VARCHAR(50) NOT NULL,
  author VARCHAR(100) NOT NULL,
  published_by VARCHAR(50) DEFAULT NULL,
  published_date VARCHAR(10) DEFAULT NULL
);